[DEFAULT]
DB_PATH = instance/finance.db #這邊用來放SQLite的，別動到

[LINE]
CHANNEL_SECRET = 2418dcc0df1888d53bfa88ab5f326a8e
CHANNEL_ACCESS_TOKEN = 5Iyu3N0OsHKmh+6Dv4O6f/e5w63B/SUvf+d8LU+TMvA8YyhInaU863mGgIix20gGLIDLRdETnFSHyyKLPxJbSHbKDIrFHEAWzS1MGUbPNxD2rPb7aVKPLEMfA86Uw4Q7MAw0hkbjJt46t2zg+EQfywdB04t89/1O/w1cDnyilFU=

[Patreon]
CLIENT_ID     = 5FqLwz30BXMNaORJKKaR5tEMRIcNjvKUYaXOGPFMVseTZhygnGLWgOp8qgnfwVtB
CLIENT_SECRET = 2KeJTjk-rXq54Gs7Qr8YFoIhe_MGOrZ_9j8U-mOBOT2J8XHFv-4PVLbkZLneMFA5
API_VERSION   = 2

[Gemini]
API_KEY=AIzaSyB3LEhqh0QOdUTth8ILTHS_KEgjTI9MbsU

[Email]
MAIL_SERVER=smtp.gmail.com
MAIL_PORT=587
MAIL_USE_TLS=True
MAIL_USERNAME=finwebfinance2025@gmail.com
MAIL_PASSWORD=iidtygmsrrpsmwfg
MAIL_DEFAULT_SENDER=finwebfinance2025@gmail.com

[ReCAPTCHA]
SECRET_KEY=6LcBfKcqAAAAAAxx_E5XpiMGNeqI_NC6ojtJNjxh

[AlphaVantage]
API_KEY=O631J2GV2ZV8UHLX

[CoinGecko]
#預留未來擴充
API_URL = https://api.coingecko.com/api/v3

[Security]
PEPPER = ewqjqiurhoiqwy4o9quoauohklau4f9p7qoahslkchlkeduqow8epocvuqwlidnyliQUMQEWUOLIDYWOIRFYEWRLINHCLIRQUWSLIEYUQWIEYUDLINKLJMKJYQKIWEUKAMJADSJDJAHSJ4325REEWFSeaerw