import type { Lang } from '../i18n/strings.js';

type Entry = Partial<Record<Exclude<Lang, 'zh-TW'>, string>>;

const entry = (zhCN: string, en: string, ja: string, ko: string): Entry => ({ 'zh-CN': zhCN, en, ja, ko });

export const LEGAL_TRANSLATIONS: Record<string, Entry> = {
  'LexTaiwan 法律導航': entry('LexTaiwan 法律导航', 'LexTaiwan Legal Navigator', 'LexTaiwan 法律ナビ', 'LexTaiwan 법률 내비게이터'),
  '台灣法規與情境分析': entry('台湾法规与情境分析', 'Taiwan law and scenario analysis', '台湾法令と状況分析', '대만 법령 및 상황 분석'),
  '用本機可解釋檢索快速整理可能涉及的台灣法規、證據與下一步。': entry(
    '使用本机可解释检索，快速整理可能涉及的台湾法规、证据与后续步骤。',
    'Use explainable on-device retrieval to organize potentially relevant Taiwan laws, evidence, and next steps.',
    '説明可能なローカル検索で、関連する可能性のある台湾法令、証拠、次の手順を整理します。',
    '설명 가능한 로컬 검색으로 관련 가능성이 있는 대만 법령, 증거와 다음 단계를 정리합니다.'
  ),
  '台灣法律': entry('台湾法律', 'Taiwan law', '台湾法', '대만 법률'),
  '智慧法律工作台': entry('智能法律工作台', 'Legal intelligence workspace', '法律インテリジェンス・ワークスペース', '법률 인텔리전스 작업 공간'),
  '法規檢索': entry('法规检索', 'Law search', '法令検索', '법령 검색'),
  '情境分析': entry('情境分析', 'Scenario analysis', '状況分析', '상황 분석'),
  '法規資料庫': entry('法规数据库', 'Law library', '法令データベース', '법령 데이터베이스'),
  '案件筆記': entry('案件笔记', 'Case notes', '案件メモ', '사건 노트'),
  '官方來源': entry('官方来源', 'Official sources', '公式情報源', '공식 출처'),
  '系統時間': entry('系统时间', 'System time', 'システム時刻', '시스템 시간'),
  '離線可用': entry('离线可用', 'Works offline', 'オフライン対応', '오프라인 사용 가능'),
  '無需 API 金鑰': entry('无需 API 密钥', 'No API key required', 'APIキー不要', 'API 키 불필요'),
  '本機可解釋檢索': entry('本机可解释检索', 'Explainable local retrieval', '説明可能なローカル検索', '설명 가능한 로컬 검색'),
  '描述發生了什麼事': entry('描述发生了什么事', 'Describe what happened', '何が起きたか説明してください', '무슨 일이 있었는지 설명하세요'),
  '請包含人物關係、時間、對方做了什麼、你有哪些文件或訊息。': entry(
    '请包含人物关系、时间、对方做了什么，以及你有哪些文件或消息。',
    'Include the relationship, timing, what the other party did, and any documents or messages you have.',
    '関係、時期、相手の行為、手元の書類やメッセージを含めてください。',
    '관계, 시점, 상대방의 행동, 보유한 문서나 메시지를 포함하세요.'
  ),
  '開始分析': entry('开始分析', 'Analyze', '分析する', '분석 시작'),
  '清除': entry('清除', 'Clear', 'クリア', '지우기'),
  '範例情境': entry('示例情境', 'Example scenarios', '例の状況', '예시 상황'),
  '公司要求我每天加班卻沒有給加班費。': entry('公司要求我每天加班却不给加班费。', 'My employer requires daily overtime without overtime pay.', '会社から毎日残業を求められますが、残業代が支払われません。', '회사가 매일 야근을 요구하지만 연장근로수당을 주지 않습니다.'),
  '網購商品到貨後想退貨，賣家說拆箱就不能退。': entry('网购商品到货后想退货，卖家说拆箱就不能退。', 'I want to return an online purchase, but the seller says opening the box cancels returns.', 'ネット購入品を返品したいのですが、開封したら返品不可と言われました。', '온라인 구매품을 반품하려는데 판매자가 개봉하면 반품할 수 없다고 합니다.'),
  '房東在退租後沒有說明原因就不退押金。': entry('房东在退租后没有说明原因就不退押金。', 'My landlord kept the deposit after move-out without explaining why.', '退去後、大家が理由を示さず敷金を返しません。', '퇴거 후 집주인이 이유 설명 없이 보증금을 돌려주지 않습니다.'),
  '我收到通知說會員個資外洩，之後出現陌生登入。': entry('我收到会员个人信息泄露通知，之后出现陌生登录。', 'I was notified of a member-data breach and then saw an unfamiliar login.', '会員情報の漏えい通知後、見覚えのないログインがありました。', '회원 개인정보 유출 통지 후 알 수 없는 로그인이 발생했습니다.'),
  '可能涉及': entry('可能涉及', 'Potentially relevant', '関連する可能性', '관련 가능성'),
  '處理優先度': entry('处理优先级', 'Priority', '対応優先度', '처리 우선순위'),
  '主要領域': entry('主要领域', 'Primary area', '主な分野', '주요 분야'),
  '相關法規': entry('相关法规', 'Relevant provisions', '関連法令', '관련 법령'),
  '待補充資訊': entry('待补充信息', 'More details needed', '追加情報が必要', '추가 정보 필요'),
  '尚未分析': entry('尚未分析', 'No analysis yet', '未分析', '분석 전'),
  '輸入具體情況後，系統會比對本機法規索引並說明命中原因。': entry(
    '输入具体情况后，系统会比对本机法规索引并说明匹配原因。',
    'Enter a specific situation to compare it with the local legal index and see why each result matched.',
    '具体的な状況を入力すると、ローカル法令索引と照合し、一致理由を表示します。',
    '구체적인 상황을 입력하면 로컬 법률 색인과 비교하고 일치 이유를 표시합니다.'
  ),
  '命中原因': entry('匹配原因', 'Why it matched', '一致した理由', '일치한 이유'),
  '建議保留的證據': entry('建议保留的证据', 'Evidence to preserve', '保存すべき証拠', '보존할 증거'),
  '下一步清單': entry('后续步骤', 'Next-step checklist', '次の手順', '다음 단계'),
  '安全優先': entry('安全优先', 'Safety first', '安全を優先', '안전 우선'),
  '一般整理': entry('一般整理', 'Routine review', '通常確認', '일반 검토'),
  '儘快處理': entry('尽快处理', 'Prompt action', '早めの対応', '신속한 조치'),
  '立即處理': entry('立即处理', 'Urgent action', '緊急対応', '긴급 조치'),
  '相關程度': entry('相关程度', 'Relevance', '関連度', '관련도'),
  '查看官方條文': entry('查看官方条文', 'Open official text', '公式条文を開く', '공식 조문 보기'),
  '搜尋法律、條號或生活用語': entry('搜索法律、条号或生活用语', 'Search a law, article, or everyday phrase', '法令、条文、日常語を検索', '법률, 조문 또는 일상어 검색'),
  '全部領域': entry('全部领域', 'All domains', '全分野', '모든 분야'),
  '條法規指引': entry('条法规指引', 'legal guides', '件の法令ガイド', '개 법령 가이드'),
  '儲存本次分析': entry('保存本次分析', 'Save this analysis', 'この分析を保存', '이번 분석 저장'),
  '尚無案件筆記': entry('暂无案件笔记', 'No case notes yet', '案件メモはまだありません', '사건 노트가 없습니다'),
  '刪除筆記': entry('删除笔记', 'Delete note', 'メモを削除', '메모 삭제'),
  '建立時間': entry('创建时间', 'Created', '作成日時', '생성 시간'),
  '最後檢核日期': entry('最后核验日期', 'Last legal review', '最終確認日', '최종 검토일'),
  '資料會留在這台裝置': entry('数据会保留在此设备', 'Data stays on this device', 'データはこの端末に保存されます', '데이터는 이 기기에만 저장됩니다'),
  '資訊用途': entry('信息用途', 'Information use', '情報の用途', '정보 용도'),
  '關閉': entry('关闭', 'Close', '閉じる', '닫기'),
  '這是本機資訊整理，不是法律意見，也不會取代律師或主管機關的判斷。': entry(
    '这是本机信息整理，不是法律意见，也不能取代律师或主管机关的判断。',
    'This on-device information organizer is not legal advice and does not replace a lawyer or competent authority.',
    'これは端末内の情報整理であり、法律相談ではなく、弁護士や所管機関の判断に代わるものではありません。',
    '이 기능은 기기 내 정보 정리 도구이며 법률 자문이 아니고 변호사나 관할 기관의 판단을 대신하지 않습니다.'
  ),
  '若有立即人身危險，先離開現場並撥打 110。': entry('如有人身危险，请先离开现场并拨打 110。', 'If there is immediate danger, leave the scene and call 110.', '身の危険がある場合は現場を離れ、110番へ連絡してください。', '즉각적인 위험이 있으면 현장을 벗어나 110에 신고하세요.'),
  '受傷或需要緊急醫療時撥打 119。': entry('受伤或需要紧急医疗时拨打 119。', 'Call 119 for injury or emergency medical care.', 'けがや救急医療が必要な場合は119番へ連絡してください。', '부상 또는 응급 의료가 필요하면 119에 신고하세요.'),
  '不要為了蒐證讓自己持續處於危險中。': entry('不要为了取证让自己持续处于危险中。', 'Do not remain in danger just to collect evidence.', '証拠収集のために危険な状況に留まらないでください。', '증거 수집을 위해 위험한 상황에 머물지 마세요.'),
  '勞動職場': entry('劳动职场', 'Employment', '労働・職場', '노동·직장'),
  '消費交易': entry('消费交易', 'Consumer transactions', '消費取引', '소비 거래'),
  '租屋與財產': entry('租房与财产', 'Housing and property', '賃貸・財産', '임대·재산'),
  '契約與損害': entry('合同与损害', 'Contracts and harm', '契約・損害', '계약·손해'),
  '個資與數位': entry('个人信息与数字', 'Privacy and digital', '個人情報・デジタル', '개인정보·디지털'),
  '家庭安全': entry('家庭安全', 'Family safety', '家庭の安全', '가정 안전'),
  '刑事風險': entry('刑事风险', 'Criminal risk', '刑事リスク', '형사 위험'),
  '訴訟與舉證': entry('诉讼与举证', 'Procedure and evidence', '訴訟・立証', '소송·입증'),
  '交通事故': entry('交通事故', 'Traffic incidents', '交通事故', '교통사고'),
  '民法': entry('民法', 'Civil Code', '民法', '민법'),
  '中華民國刑法': entry('中华民国刑法', 'Criminal Code', '中華民国刑法', '중화민국 형법'),
  '勞動基準法': entry('劳动基准法', 'Labor Standards Act', '労働基準法', '근로기준법'),
  '消費者保護法': entry('消费者保护法', 'Consumer Protection Act', '消費者保護法', '소비자보호법'),
  '個人資料保護法': entry('个人资料保护法', 'Personal Data Protection Act', '個人情報保護法', '개인정보보호법'),
  '性別平等工作法': entry('性别平等工作法', 'Gender Equality in Employment Act', '雇用における男女平等法', '고용 성평등법'),
  '家庭暴力防治法': entry('家庭暴力防治法', 'Domestic Violence Prevention Act', '家庭暴力防止法', '가정폭력방지법'),
  '民事訴訟法': entry('民事诉讼法', 'Code of Civil Procedure', '民事訴訟法', '민사소송법'),
  '道路交通管理處罰條例': entry('道路交通管理处罚条例', 'Road Traffic Management and Penalty Act', '道路交通管理処罰条例', '도로교통관리처벌조례'),
  '法律扶助基金會': entry('法律扶助基金会', 'Legal Aid Foundation', '法律扶助基金会', '법률구조재단'),
  '法務部全國法規資料庫': entry('法务部全国法规数据库', 'Ministry of Justice Laws and Regulations Database', '法務部全国法規データベース', '법무부 전국 법령 데이터베이스'),
  '財團法人法律扶助基金會': entry('财团法人法律扶助基金会', 'Legal Aid Foundation', '法律扶助基金会', '법률구조재단'),
  '延長工時工資': entry('延长工时工资', 'Overtime pay', '時間外労働賃金', '연장근로수당'),
  '正常工時與出勤紀錄': entry('正常工时与出勤记录', 'Working hours and attendance records', '通常労働時間と出勤記録', '정상 근로시간 및 출근 기록'),
  '終止契約預告': entry('终止合同预告', 'Notice of employment termination', '雇用契約終了の予告', '근로계약 종료 예고'),
  '性別與家庭責任歧視禁止': entry('禁止性别与家庭责任歧视', 'Protection from sex and family-status discrimination', '性別・家庭責任による差別の禁止', '성별 및 가족책임 차별 금지'),
  '通訊交易解除權': entry('远程交易解除权', 'Right to cancel distance transactions', '通信販売の契約解除権', '통신판매 계약 철회권'),
  '商品與服務安全': entry('商品与服务安全', 'Product and service safety', '商品・サービスの安全', '상품 및 서비스 안전'),
  '無法律上原因受利益': entry('无法律原因取得利益', 'Unjust enrichment', '不当利得', '부당이득'),
  '租賃物所有權移轉': entry('租赁物所有权转移', 'Transfer of leased property ownership', '賃貸物の所有権移転', '임대물 소유권 이전'),
  '侵權行為損害賠償': entry('侵权行为损害赔偿', 'Damages for tortious conduct', '不法行為による損害賠償', '불법행위 손해배상'),
  '不完全給付': entry('不完全履行', 'Defective performance', '不完全履行', '불완전이행'),
  '所有物返還與妨害排除': entry('所有物返还与妨害排除', 'Return of property and removal of interference', '所有物返還・妨害排除', '소유물 반환 및 방해 제거'),
  '非公務機關蒐集個資': entry('非公务机关收集个人信息', 'Personal-data collection by private entities', '民間事業者による個人情報収集', '민간기관의 개인정보 수집'),
  '個資利用範圍': entry('个人信息利用范围', 'Permitted use of personal data', '個人情報の利用範囲', '개인정보 이용 범위'),
  '個資安全維護': entry('个人信息安全维护', 'Personal-data security safeguards', '個人情報の安全管理', '개인정보 안전조치'),
  '違法個資處理的損害賠償': entry('违法处理个人信息的损害赔偿', 'Damages for unlawful personal-data processing', '違法な個人情報処理の損害賠償', '위법한 개인정보 처리 손해배상'),
  '保護令聲請': entry('保护令申请', 'Application for a protection order', '保護命令の申立て', '보호명령 신청'),
  '恐嚇危害安全': entry('恐吓危害安全', 'Threats to personal safety', '安全を害する脅迫', '안전을 해치는 협박'),
  '誹謗': entry('诽谤', 'Defamation', '名誉毀損', '명예훼손'),
  '詐欺取財': entry('诈骗取财', 'Fraudulent acquisition of property', '詐欺による財物取得', '사기 재산취득'),
  '舉證責任': entry('举证责任', 'Burden of proof', '立証責任', '입증책임'),
  '交通事故處置義務': entry('交通事故处置义务', 'Duties after a traffic accident', '交通事故後の措置義務', '교통사고 후 조치 의무'),
  '勞動與職場相關條文摘要': entry('涵盖工时、工资、解雇与职场平等；实际适用仍须依雇佣关系与证据判断。', 'Covers working hours, pay, termination, and workplace equality. Application depends on the employment relationship and evidence.', '労働時間、賃金、解雇、職場の平等に関する規定です。適用は雇用関係と証拠により異なります。', '근로시간, 임금, 해고 및 직장 내 평등을 다룹니다. 적용 여부는 고용관계와 증거에 따라 달라집니다.'),
  '消費交易相關條文摘要': entry('涵盖远程交易解除权及商品、服务安全；须确认交易方式与法定例外。', 'Covers distance-sale cancellation rights and product or service safety. The transaction type and statutory exceptions matter.', '通信販売の解除権と商品・サービスの安全を扱います。取引形態と法定例外の確認が必要です。', '통신판매 철회권과 상품·서비스 안전을 다룹니다. 거래 유형과 법정 예외를 확인해야 합니다.'),
  '居住與財產相關條文摘要': entry('涵盖押金、租赁与所有权争议；合同、付款和点交记录通常很重要。', 'Covers deposits, leases, and ownership disputes. Contracts, payment records, and handover evidence are usually important.', '敷金、賃貸借、所有権の紛争を扱います。契約、支払、引渡しの記録が重要です。', '보증금, 임대차 및 소유권 분쟁을 다룹니다. 계약서, 지급 및 인도 기록이 중요합니다.'),
  '契約與損害相關條文摘要': entry('涵盖履约瑕疵、侵权与损害赔偿；须整理义务内容、因果关系与损失。', 'Covers defective performance, torts, and damages. Identify the duty, causation, and documented loss.', '契約不履行、不法行為、損害賠償を扱います。義務、因果関係、損害の整理が必要です。', '계약상 하자, 불법행위 및 손해배상을 다룹니다. 의무, 인과관계와 손해를 정리해야 합니다.'),
  '個資與數位相關條文摘要': entry('涵盖个人信息收集、利用、安全与损害；须确认告知内容、目的和安全措施。', 'Covers personal-data collection, use, security, and damages. Check the notice, purpose, and safeguards.', '個人情報の収集、利用、安全管理、損害を扱います。通知、目的、安全措置の確認が必要です。', '개인정보 수집, 이용, 안전조치와 손해를 다룹니다. 고지, 목적 및 보호조치를 확인해야 합니다.'),
  '家庭安全相關條文摘要': entry('涉及家庭暴力与保护令；如有立即危险，应先离开现场并联络紧急服务。', 'Covers domestic violence and protection orders. If danger is immediate, leave the scene and contact emergency services first.', '家庭内暴力と保護命令を扱います。危険が迫っている場合は避難し、緊急機関へ連絡してください。', '가정폭력과 보호명령을 다룹니다. 즉각적인 위험이 있으면 먼저 대피하고 긴급기관에 연락하세요.'),
  '刑事風險相關條文摘要': entry('涵盖恐吓、诽谤与诈骗等风险；言论、金流和联络记录可能影响判断。', 'Covers risks such as threats, defamation, and fraud. Statements, money flows, and communication records may be decisive.', '脅迫、名誉毀損、詐欺などを扱います。発言、資金の流れ、連絡記録が判断に影響します。', '협박, 명예훼손, 사기 등의 위험을 다룹니다. 발언, 자금 흐름과 연락 기록이 중요할 수 있습니다.'),
  '程序與證據相關條文摘要': entry('说明民事程序中的举证分配；应先确认哪些事实由哪一方证明。', 'Explains allocation of proof in civil proceedings. Identify which party must establish each disputed fact.', '民事手続の立証分担を扱います。争点ごとに誰が立証すべきか確認してください。', '민사절차의 입증 분담을 설명합니다. 각 쟁점 사실을 누가 입증해야 하는지 확인하세요.'),
  '交通事故相關條文摘要': entry('涵盖事故后的停车、救护、报警与现场处置义务；安全和救护优先。', 'Covers duties to stop, assist, report, and handle the scene after a traffic accident. Safety and medical aid come first.', '交通事故後の停止、救護、通報、現場対応義務を扱います。安全と救護を優先してください。', '교통사고 후 정차, 구호, 신고 및 현장조치 의무를 다룹니다. 안전과 응급구호가 우선입니다.'),
  '保留原始文件、訊息與檔案中繼資料': entry('保留原始文件、消息与文件元数据', 'Keep original documents, messages, and file metadata', '原本の書類、メッセージ、ファイルのメタデータを保存する', '원본 문서, 메시지 및 파일 메타데이터 보관'),
  '依時間順序整理事件與聯絡紀錄': entry('按时间顺序整理事件与联系记录', 'Build a chronological record of events and communications', '出来事と連絡記録を時系列で整理する', '사건과 연락 기록을 시간순으로 정리'),
  '保存契約、收據、照片與相關證明': entry('保存合同、收据、照片与相关证明', 'Preserve contracts, receipts, photos, and supporting records', '契約書、領収書、写真、関連資料を保存する', '계약서, 영수증, 사진 및 관련 증빙 보관'),
  '開啟官方法規確認現行條文與例外': entry('打开官方法规确认现行条文与例外', 'Check the current official text and statutory exceptions', '公式法令で現行条文と例外を確認する', '공식 법령에서 현행 조문과 예외 확인'),
  '以可保存的書面方式提出要求或通知': entry('以可保存的书面方式提出要求或通知', 'Send requests or notices in a form you can preserve', '保存可能な書面で要求または通知を行う', '보존 가능한 서면 방식으로 요구 또는 통지'),
  '視情況洽詢主管機關、法律扶助或律師': entry('视情况咨询主管机关、法律援助或律师', 'Contact the competent authority, legal aid, or a lawyer as appropriate', '必要に応じて主管機関、法律扶助、弁護士に相談する', '필요시 관할기관, 법률구조 또는 변호사에게 상담'),
  '情境詞與法規主題相符': entry('情境词与法规主题相符', 'Scenario terms match this legal topic', '状況の語句がこの法的テーマと一致', '상황의 표현이 해당 법률 주제와 일치')
};
