"""Generate web/countries.generated.js for ALL countries from a restcountries snapshot.

  python tools/gen_countries.py     # uses data/_rc.json (fetch it first, see below)

Fetch the snapshot once:
  curl "https://restcountries.com/v3.1/all?fields=cca2,name,latlng,region,subregion,languages,translations,unMember" -o data/_rc.json
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
rc = json.loads((ROOT / "data" / "_rc.json").read_text(encoding="utf-8"))

# Simplified -> Traditional (Taiwan phrasing) so names match the zh-TW default.
try:
    from opencc import OpenCC
    _cc = OpenCC("s2twp")
    def s2t(s):
        return _cc.convert(s)
except Exception:
    def s2t(s):
        return s


def region_of(c):
    sub = (c.get("subregion") or "")
    reg = (c.get("region") or "")
    if sub in ("Western Asia", "Northern Africa"):
        return "mideast"   # group MENA together culturally
    if reg == "Asia":
        return "asia"
    if reg == "Europe":
        return "europe"
    if reg == "Africa":
        return "africa"
    if reg == "Americas":
        return "americas"
    if reg == "Oceania":
        return "oceania"
    return None  # Antarctic / unknown -> skip


rows = []
for c in rc:
    iso = (c.get("cca2") or "").lower()
    if not iso:
        continue
    if not c.get("unMember") and iso != "tw":
        continue
    reg = region_of(c)
    if not reg:
        continue
    ll = c.get("latlng") or [0, 0]
    if len(ll) < 2:
        continue
    en = c["name"]["common"]
    zh = s2t((c.get("translations", {}).get("zho", {}) or {}).get("common") or en)
    langs = list((c.get("languages") or {}).values())
    lang = langs[0] if langs else "English"
    rows.append({
        "id": iso, "zh": zh, "en": en,
        "lat": round(float(ll[0]), 2), "lon": round(float(ll[1]), 2),
        "region": reg, "lang": lang
    })

rows.sort(key=lambda r: r["id"])

lines = ["// AUTO-GENERATED by tools/gen_countries.py from a restcountries snapshot.",
         "// All UN members (+ Taiwan). Do not edit by hand; re-run the generator.",
         "export const COUNTRY_TABLE = ["]
for r in rows:
    zh = r["zh"].replace("\\", "").replace('"', '\\"')
    en = r["en"].replace('"', '\\"')
    lang = r["lang"].replace('"', '\\"')
    lines.append(
        f'  {{ id: "{r["id"]}", zh: "{zh}", en: "{en}", lat: {r["lat"]}, lon: {r["lon"]}, region: "{r["region"]}", lang: "{lang}" }},'
    )
lines.append("];")

out = ROOT / "web" / "countries.generated.js"
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {len(rows)} countries -> {out}")

# region tally
from collections import Counter
print(Counter(r["region"] for r in rows))
