import type { Lang } from '../i18n/strings.js';

type Entry = Partial<Record<Exclude<Lang, 'zh-TW'>, string>>;

const entry = (zhCN: string, en: string, ja: string, ko: string): Entry => ({ 'zh-CN': zhCN, en, ja, ko });

export const NEURO_TRANSLATIONS: Record<string, Entry> = {
  'NeuroFlow AI': entry('NeuroFlow AI', 'NeuroFlow AI', 'NeuroFlow AI', 'NeuroFlow AI'),
  '智慧推論與神經動態工作室': entry('智能推理与神经动态工作室', 'Intelligence and neural dynamics studio', '知能推論・神経ダイナミクススタジオ', '지능 추론 및 신경 동역학 스튜디오'),
  '把連網檢索、本機推論、Transformer、RL 與液態神經網路整合成可操作的 AI 實驗室。': entry(
    '把联网检索、本机推理、Transformer、RL 与液态神经网络整合成可操作的 AI 实验室。',
    'Combine connected retrieval, local inference, Transformers, RL, and liquid neural networks in an operable AI lab.',
    'オンライン検索、ローカル推論、Transformer、RL、液体ニューラルネットワークを操作可能な AI ラボに統合します。',
    '온라인 검색, 로컬 추론, Transformer, RL, 액체 신경망을 조작 가능한 AI 실험실로 통합합니다.'
  ),
  '人工智慧': entry('人工智能', 'Artificial intelligence', '人工知能', '인공지능'),
  '神經網路': entry('神经网络', 'Neural network', 'ニューラルネットワーク', '신경망'),
  '本機推論': entry('本机推理', 'Local inference', 'ローカル推論', '로컬 추론'),
  'LNN': entry('LNN', 'LNN', 'LNN', 'LNN'),
  '3D 推論引擎': entry('3D 推理引擎', '3D inference engine', '3D 推論エンジン', '3D 추론 엔진'),
  'NeuroFlow 導覽': entry('NeuroFlow 导航', 'NeuroFlow navigation', 'NeuroFlow ナビゲーション', 'NeuroFlow 탐색'),
  '推論工作台': entry('推理工作台', 'Inference workspace', '推論ワークスペース', '추론 작업대'),
  '獎勵與 LNN': entry('奖励与 LNN', 'Reward & LNN', '報酬と LNN', '보상 및 LNN'),
  '知識來源': entry('知识来源', 'Knowledge sources', '知識ソース', '지식 출처'),
  '實驗紀錄': entry('实验记录', 'Experiment history', '実験履歴', '실험 기록'),
  '模型架構': entry('模型架构', 'Model architecture', 'モデル構成', '모델 구조'),
  '節點': entry('节点', 'Nodes', 'ノード', '노드'),
  '連結': entry('连接', 'Connections', '接続', '연결'),
  'Token': entry('Token', 'Tokens', 'トークン', '토큰'),
  '獎勵': entry('奖励', 'Reward', '報酬', '보상'),
  '模擬速度': entry('模拟速度', 'Simulation speed', 'シミュレーション速度', '시뮬레이션 속도'),
  '免金鑰': entry('免密钥', 'No API key', 'API キー不要', 'API 키 불필요'),
  '網路可用': entry('网络可用', 'Network available', 'ネットワーク利用可', '네트워크 사용 가능'),
  '離線': entry('离线', 'Offline', 'オフライン', '오프라인'),
  '本機備援': entry('本机备用', 'Local fallback', 'ローカル予備', '로컬 대체'),
  '系統時間': entry('系统时间', 'System time', 'システム時刻', '시스템 시간'),
  '關閉': entry('关闭', 'Close', '閉じる', '닫기'),
  '即時推論': entry('实时推理', 'Live inference', 'ライブ推論', '실시간 추론'),
  '輸入問題': entry('输入问题', 'Enter a question', '質問を入力', '질문 입력'),
  '自動': entry('自动', 'Auto', '自動', '자동'),
  '連網': entry('联网', 'Online', 'オンライン', '온라인'),
  '本機': entry('本机', 'Local', 'ローカル', '로컬'),
  '執行推論': entry('执行推理', 'Run inference', '推論を実行', '추론 실행'),
  '推論中': entry('推理中', 'Running', '推論中', '추론 중'),
  '生成中': entry('生成中', 'Generating', '生成中', '생성 중'),
  '推論意圖': entry('推理意图', 'Intent', '推論の意図', '추론 의도'),
  '比較分析': entry('比较分析', 'Comparison', '比較分析', '비교 분석'),
  '解釋說明': entry('解释说明', 'Explanation', '解説', '설명'),
  '定義': entry('定义', 'Definition', '定義', '정의'),
  '成因與影響': entry('成因与影响', 'Cause & effect', '要因と影響', '원인과 영향'),
  '綜合': entry('综合', 'General', '総合', '종합'),
  '輸出 Token': entry('输出 Token', 'Output tokens', '出力トークン', '출력 토큰'),
  '動態神經路徑': entry('动态神经路径', 'Dynamic neural path', '動的ニューラル経路', '동적 신경 경로'),
  '3D 神經網路動態視覺化': entry('3D 神经网络动态可视化', '3D neural network dynamics', '3D ニューラルネットワーク動態可視化', '3D 신경망 동역학 시각화'),
  '生成結果': entry('生成结果', 'Generated result', '生成結果', '생성 결과'),
  '筆證據': entry('条证据', 'evidence items', '件の根拠', '개 근거'),
  '執行推論後，答案與證據會顯示在這裡。': entry('执行推理后，答案与证据会显示在这里。', 'The answer and evidence will appear here after inference.', '推論後、回答と根拠がここに表示されます。', '추론 후 답변과 근거가 여기에 표시됩니다.'),
  '用簡單方式解釋大型語言模型如何產生答案': entry('用简单方式解释大型语言模型如何生成答案', 'Explain simply how a large language model produces an answer', '大規模言語モデルが回答を生成する仕組みを簡単に説明して', '대규모 언어 모델이 답변을 만드는 방식을 쉽게 설명해 줘'),
  '液態神經網路和 Transformer 有什麼差異？': entry('液态神经网络和 Transformer 有什么差异？', 'How do liquid neural networks differ from Transformers?', '液体ニューラルネットワークと Transformer の違いは？', '액체 신경망과 Transformer의 차이는 무엇인가요?'),
  'RLHF 的獎勵如何影響模型輸出？': entry('RLHF 的奖励如何影响模型输出？', 'How does RLHF reward affect model output?', 'RLHF の報酬はモデル出力にどう影響しますか？', 'RLHF 보상은 모델 출력에 어떤 영향을 주나요?'),
  'Token 化': entry('Token 化', 'Tokenize', 'トークン化', '토큰화'),
  '向量嵌入': entry('向量嵌入', 'Embedding', '埋め込み', '임베딩'),
  '注意力': entry('注意力', 'Attention', '注意機構', '어텐션'),
  '液態狀態': entry('液态状态', 'Liquid state', '液体状態', '액체 상태'),
  '獎勵評估': entry('奖励评估', 'Reward scoring', '報酬評価', '보상 평가'),
  '答案解碼': entry('答案解码', 'Decode', '回答デコード', '답변 디코딩'),
  '線上知識': entry('在线知识', 'Online knowledge', 'オンライン知識', '온라인 지식'),
  '本機模式': entry('本机模式', 'Local mode', 'ローカルモード', '로컬 모드'),
  '連線中': entry('连接中', 'Connecting', '接続中', '연결 중'),
  '來源錯誤': entry('来源错误', 'Source error', 'ソースエラー', '출처 오류'),
  '待命': entry('待命', 'Ready', '待機', '대기'),
  '訊號傳播與注意力': entry('信号传播与注意力', 'Signal flow and attention', '信号伝播と注意機構', '신호 전파 및 어텐션'),
  '播放': entry('播放', 'Play', '再生', '재생'),
  '暫停': entry('暂停', 'Pause', '一時停止', '일시정지'),
  'Token 活化': entry('Token 激活', 'Token activation', 'トークン活性化', '토큰 활성화'),
  '注意力矩陣': entry('注意力矩阵', 'Attention matrix', '注意行列', '어텐션 행렬'),
  '動態控制': entry('动态控制', 'Dynamics control', 'ダイナミクス制御', '동역학 제어'),
  '獎勵與液態狀態': entry('奖励与液态状态', 'Reward and liquid state', '報酬と液体状態', '보상 및 액체 상태'),
  '連續時間狀態': entry('连续时间状态', 'Continuous-time state', '連続時間状態', '연속 시간 상태'),
  '液態神經網路狀態圖': entry('液态神经网络状态图', 'Liquid neural network state chart', '液体ニューラルネットワーク状態図', '액체 신경망 상태 차트'),
  'LNN 參數': entry('LNN 参数', 'LNN parameters', 'LNN パラメータ', 'LNN 매개변수'),
  '時間常數': entry('时间常数', 'Time constant', '時定数', '시간 상수'),
  '回饋強度': entry('反馈强度', 'Recurrence', '再帰強度', '순환 강도'),
  '阻尼': entry('阻尼', 'Damping', '減衰', '감쇠'),
  'RL 獎勵混合': entry('RL 奖励混合', 'RL reward mix', 'RL 報酬ミックス', 'RL 보상 혼합'),
  '正確性': entry('正确性', 'Accuracy', '正確性', '정확성'),
  '有用性': entry('有用性', 'Helpfulness', '有用性', '유용성'),
  '安全性': entry('安全性', 'Safety', '安全性', '안전성'),
  '清晰度': entry('清晰度', 'Clarity', '明瞭さ', '명확성'),
  '連網檢索與本機備援': entry('联网检索与本机备用', 'Online retrieval and local fallback', 'オンライン検索とローカル予備', '온라인 검색 및 로컬 대체'),
  '公開知識': entry('公共知识', 'Public knowledge', '公開知識', '공개 지식'),
  '免金鑰 · 連網優先': entry('免密钥 · 联网优先', 'No key · online first', 'キー不要・オンライン優先', '키 불필요 · 온라인 우선'),
  '可用': entry('可用', 'Available', '利用可能', '사용 가능'),
  '本機知識': entry('本机知识', 'Local knowledge', 'ローカル知識', '로컬 지식'),
  '斷線可用 · 即時檢索': entry('断网可用 · 实时检索', 'Offline ready · live retrieval', 'オフライン対応・即時検索', '오프라인 지원 · 실시간 검색'),
  '就緒': entry('就绪', 'Ready', '準備完了', '준비됨'),
  '加入工作區知識': entry('加入工作区知识', 'Add workspace knowledge', 'ワークスペース知識を追加', '작업 공간 지식 추가'),
  '標題': entry('标题', 'Title', 'タイトル', '제목'),
  '內容': entry('内容', 'Content', '内容', '내용'),
  '加入': entry('加入', 'Add', '追加', '추가'),
  '目前證據': entry('当前证据', 'Current evidence', '現在の根拠', '현재 근거'),
  '開啟來源': entry('打开来源', 'Open source', 'ソースを開く', '출처 열기'),
  '執行推論或加入工作區知識後，證據會顯示在這裡。': entry('执行推理或加入工作区知识后，证据会显示在这里。', 'Evidence appears here after inference or adding workspace knowledge.', '推論または知識追加後、根拠がここに表示されます。', '추론하거나 작업 공간 지식을 추가하면 근거가 여기에 표시됩니다.'),
  '推論執行紀錄': entry('推理执行记录', 'Inference run history', '推論実行履歴', '추론 실행 기록'),
  '匯出 JSON': entry('导出 JSON', 'Export JSON', 'JSON をエクスポート', 'JSON 내보내기'),
  '時間': entry('时间', 'Time', '時刻', '시간'),
  '提示': entry('提示', 'Prompt', 'プロンプト', '프롬프트'),
  '模式': entry('模式', 'Mode', 'モード', '모드'),
  '延遲': entry('延迟', 'Latency', '遅延', '지연'),
  '尚無實驗紀錄': entry('暂无实验记录', 'No experiment history', '実験履歴はありません', '실험 기록 없음'),
  '完成一次推論後會自動保留。': entry('完成一次推理后会自动保留。', 'Runs are saved automatically after inference.', '推論完了後に自動保存されます。', '추론 완료 후 자동 저장됩니다.'),
  '推論管線': entry('推理管线', 'Inference pipeline', '推論パイプライン', '추론 파이프라인'),
  '即時遙測': entry('实时遥测', 'Live telemetry', 'ライブテレメトリ', '실시간 원격 측정'),
  '來源': entry('来源', 'Source', 'ソース', '출처'),
  '架構': entry('架构', 'Architecture', '構成', '구조'),
  '估計延遲': entry('估计延迟', 'Estimated latency', '推定遅延', '예상 지연'),
  '實際延遲': entry('实际延迟', 'Actual latency', '実測遅延', '실제 지연'),
  '證據': entry('证据', 'Evidence', '根拠', '근거'),
  '上下文': entry('上下文', 'Context', 'コンテキスト', '컨텍스트'),
  '來源追蹤': entry('来源追踪', 'Source trace', 'ソース追跡', '출처 추적'),
  '目前沒有來源活動。': entry('当前没有来源活动。', 'No source activity yet.', 'ソース活動はまだありません。', '아직 출처 활동이 없습니다.')
};
