import type { Lang } from '../i18n/strings.js';

type Entry = Partial<Record<Exclude<Lang, 'zh-TW'>, string>>;

const entry = (zhCN: string, en: string, ja: string, ko: string): Entry => ({
  'zh-CN': zhCN,
  en,
  ja,
  ko
});

export const SPORTS_TRANSLATIONS: Record<string, Entry> = {
  '全球體育中心': entry('全球体育中心', 'Global Sports Center', 'グローバルスポーツセンター', '글로벌 스포츠 센터'),
  '即時比分、賽程與 AI 預測': entry('实时比分、赛程与 AI 预测', 'Live scores, schedules and AI predictions', 'ライブスコア、日程、AI予測', '실시간 점수, 일정 및 AI 예측'),
  '追蹤大型體育賽事，使用蒙地卡羅模擬比較隊伍、選手與賽前勝率。': entry(
    '追踪大型体育赛事，使用蒙特卡洛模拟比较队伍、选手与赛前胜率。',
    'Follow major sporting events and use Monte Carlo simulations to compare teams, players, and pregame win probabilities.',
    '主要スポーツ大会を追跡し、モンテカルロシミュレーションでチーム、選手、試合前勝率を比較します。',
    '주요 스포츠 대회를 추적하고 몬테카를로 시뮬레이션으로 팀, 선수 및 경기 전 승률을 비교합니다.'
  ),
  '即時比分': entry('实时比分', 'live scores', 'ライブスコア', '실시간 점수'),
  '世界盃': entry('世界杯', 'World Cup', 'ワールドカップ', '월드컵'),
  '蒙地卡羅': entry('蒙特卡洛', 'Monte Carlo', 'モンテカルロ', '몬테카를로'),
  'AI 分析': entry('AI 分析', 'AI analysis', 'AI分析', 'AI 분석'),
  '免金鑰資料': entry('免密钥数据', 'No-key data', 'キー不要データ', '키 없는 데이터'),
  '賽事中心': entry('赛事中心', 'Events', '試合センター', '경기 센터'),
  '預測實驗室': entry('预测实验室', 'Prediction Lab', '予測ラボ', '예측 실험실'),
  '比較與 AI': entry('比较与 AI', 'Compare & AI', '比較とAI', '비교 및 AI'),
  '所有運動': entry('所有运动', 'All sports', 'すべての競技', '모든 스포츠'),
  '所有賽事': entry('所有赛事', 'All competitions', 'すべての大会', '모든 대회'),
  '賽事篩選': entry('赛事筛选', 'Event filters', '試合フィルター', '경기 필터'),
  '焦點賽事': entry('焦点赛事', 'Featured events', '注目の試合', '주요 경기'),
  '搜尋賽事或隊伍': entry('搜索赛事或队伍', 'Search events or teams', '試合またはチームを検索', '경기 또는 팀 검색'),
  '個人收藏': entry('个人收藏', 'Favorites', 'お気に入り', '즐겨찾기'),
  '收藏': entry('收藏', 'Favorite', 'お気に入り', '즐겨찾기'),
  '全部': entry('全部', 'All', 'すべて', '전체'),
  '重新整理': entry('刷新', 'Refresh', '更新', '새로 고침'),
  '關閉體育中心': entry('关闭体育中心', 'Close Sports Center', 'スポーツセンターを閉じる', '스포츠 센터 닫기'),
  '今天': entry('今天', 'Today', '今日', '오늘'),
  '上一天': entry('前一天', 'Previous day', '前の日', '이전 날'),
  '下一天': entry('后一天', 'Next day', '次の日', '다음 날'),
  '即時': entry('实时', 'Live', 'ライブ', '실시간'),
  '已結束': entry('已结束', 'Final', '終了', '종료'),
  '即將開始': entry('即将开始', 'Upcoming', '開始予定', '예정'),
  '延期': entry('延期', 'Postponed', '延期', '연기'),
  '取消': entry('取消', 'Cancelled', '中止', '취소'),
  '資料來源': entry('数据来源', 'Data source', 'データソース', '데이터 소스'),
  '更新於': entry('更新于', 'Updated', '更新', '업데이트'),
  '正在同步賽事資料...': entry('正在同步赛事数据...', 'Syncing sports data...', 'スポーツデータを同期中...', '스포츠 데이터를 동기화하는 중...'),
  '目前沒有符合條件的賽事': entry('目前没有符合条件的赛事', 'No matching events', '一致する試合はありません', '일치하는 경기가 없습니다'),
  '切換日期或賽事分類以查看其他內容。': entry('切换日期或赛事分类以查看其他内容。', 'Change the date or competition filter to see more.', '日付または大会フィルターを変更してください。', '날짜 또는 대회 필터를 변경해 보세요.'),
  'ESPN 公開比分': entry('ESPN 公开比分', 'ESPN public scores', 'ESPN公開スコア', 'ESPN 공개 점수'),
  '內建賽程': entry('内置赛程', 'Bundled schedule', '内蔵日程', '내장 일정'),
  '公開比分': entry('公开比分', 'Public scores', '公開スコア', '공개 점수'),
  '內建備援': entry('内置备用', 'Bundled fallback', '内蔵フォールバック', '내장 대체 데이터'),
  '快取資料': entry('缓存数据', 'Cached data', 'キャッシュデータ', '캐시 데이터'),
  '系統同步': entry('系统同步', 'System synchronized', 'システム同期', '시스템 동기화'),
  '場地': entry('场地', 'Venue', '会場', '장소'),
  '開賽時間': entry('开赛时间', 'Start time', '開始時刻', '시작 시간'),
  '賽事狀態': entry('赛事状态', 'Event status', '試合状況', '경기 상태'),
  '未提供場地': entry('未提供场地', 'Venue unavailable', '会場未定', '장소 정보 없음'),
  '模型設定': entry('模型设置', 'Model settings', 'モデル設定', '모델 설정'),
  '穩健': entry('稳健', 'Conservative', '保守的', '보수적'),
  '平衡': entry('平衡', 'Balanced', 'バランス', '균형'),
  '冷門敏感': entry('冷门敏感', 'Upset-sensitive', '番狂わせ重視', '이변 민감'),
  '模擬次數': entry('模拟次数', 'Simulations', 'シミュレーション回数', '시뮬레이션 횟수'),
  '執行預測': entry('执行预测', 'Run prediction', '予測を実行', '예측 실행'),
  '正在模擬...': entry('正在模拟...', 'Simulating...', 'シミュレーション中...', '시뮬레이션 중...'),
  '主隊': entry('主队', 'Home', 'ホーム', '홈'),
  '客隊': entry('客队', 'Away', 'アウェイ', '원정'),
  '選手 A': entry('选手 A', 'Participant A', '選手A', '참가자 A'),
  '選手 B': entry('选手 B', 'Participant B', '選手B', '참가자 B'),
  '評分': entry('评分', 'Rating', 'レーティング', '평점'),
  '進攻': entry('进攻', 'Offense', '攻撃', '공격'),
  '防守': entry('防守', 'Defense', '守備', '수비'),
  '近期狀態': entry('近期状态', 'Recent form', '最近の調子', '최근 폼'),
  '勝率': entry('胜率', 'Win probability', '勝率', '승리 확률'),
  '和局': entry('平局', 'Draw', '引き分け', '무승부'),
  '預測比分': entry('预测比分', 'Projected score', '予想スコア', '예상 점수'),
  '模型信心': entry('模型信心', 'Model confidence', 'モデル信頼度', '모델 신뢰도'),
  '可能比分': entry('可能比分', 'Likely scores', '有力スコア', '가능성 높은 점수'),
  '模型說明': entry('模型说明', 'Model notes', 'モデル説明', '모델 설명'),
  '蒙地卡羅模擬': entry('蒙特卡洛模拟', 'Monte Carlo simulation', 'モンテカルロシミュレーション', '몬테카를로 시뮬레이션'),
  '僅供學習與賽事分析，不構成投注建議。': entry('仅供学习与赛事分析，不构成投注建议。', 'For learning and event analysis only. This is not betting advice.', '学習と試合分析のみを目的とし、賭けの助言ではありません。', '학습 및 경기 분석용이며 베팅 조언이 아닙니다.'),
  '隊伍／選手比較': entry('队伍／选手比较', 'Team / player comparison', 'チーム／選手比較', '팀 / 선수 비교'),
  '指標': entry('指标', 'Metric', '指標', '지표'),
  '本機 AI 賽前報告': entry('本机 AI 赛前报告', 'Local AI pregame report', 'ローカルAI試合前レポート', '로컬 AI 경기 전 보고서'),
  '產生 AI 分析': entry('生成 AI 分析', 'Generate AI analysis', 'AI分析を生成', 'AI 분석 생성'),
  '分析中...': entry('分析中...', 'Analyzing...', '分析中...', '분석 중...'),
  '本機規則': entry('本机规则', 'Local rules', 'ローカルルール', '로컬 규칙'),
  'Ollama 本機模型': entry('Ollama 本机模型', 'Local Ollama model', 'ローカルOllamaモデル', '로컬 Ollama 모델'),
  '未選擇賽事': entry('未选择赛事', 'No event selected', '試合が選択されていません', '선택된 경기 없음'),
  '請先從賽事中心選擇一場可比較的賽事。': entry('请先从赛事中心选择一场可比较的赛事。', 'Choose a comparable event from the event center first.', 'まず試合センターから比較可能な試合を選択してください。', '먼저 경기 센터에서 비교할 경기를 선택하세요.'),
  '資料模式': entry('数据模式', 'Data mode', 'データモード', '데이터 모드'),
  '線上': entry('在线', 'Online', 'オンライン', '온라인'),
  '離線備援': entry('离线备用', 'Offline fallback', 'オフライン代替', '오프라인 대체'),
  '快取': entry('缓存', 'Cache', 'キャッシュ', '캐시'),
  '支援項目': entry('支持项目', 'Capabilities', '機能', '기능'),
  '免 API Key': entry('免 API Key', 'No API key', 'APIキー不要', 'API 키 불필요'),
  '本機運算': entry('本机运算', 'Local compute', 'ローカル計算', '로컬 연산'),
  '隱私優先': entry('隐私优先', 'Privacy first', 'プライバシー優先', '개인정보 우선'),
  '資料更新失敗，已顯示可用內容。': entry('数据更新失败，已显示可用内容。', 'Update failed. Available data is still shown.', '更新に失敗しました。利用可能なデータを表示しています。', '업데이트에 실패했습니다. 사용 가능한 데이터를 표시합니다.'),
  '遠端更新失敗，顯示快取資料。': entry('远端更新失败，显示缓存数据。', 'Remote update failed. Showing cached data.', 'リモート更新に失敗したため、キャッシュデータを表示します。', '원격 업데이트에 실패하여 캐시 데이터를 표시합니다.'),
  '預測完成': entry('预测完成', 'Prediction complete', '予測完了', '예측 완료'),
  '選擇賽事後即可執行模型': entry('选择赛事后即可执行模型', 'Select an event to run the model', '試合を選択してモデルを実行', '경기를 선택해 모델 실행'),
  '目前比分': entry('当前比分', 'Current score', '現在のスコア', '현재 점수'),
  '尚未開賽': entry('尚未开赛', 'Not started', '開始前', '경기 전'),
  '場賽事': entry('场赛事', 'events', '試合', '경기'),
  '共 {0} 場': entry('共 {0} 场', '{0} events', '全{0}試合', '총 {0}경기'),
  '足球': entry('足球', 'Football', 'サッカー', '축구'),
  '籃球': entry('篮球', 'Basketball', 'バスケットボール', '농구'),
  '棒球': entry('棒球', 'Baseball', '野球', '야구'),
  '美式足球': entry('美式足球', 'American football', 'アメリカンフットボール', '미식축구'),
  '冰球': entry('冰球', 'Ice hockey', 'アイスホッケー', '아이스하키'),
  '賽車': entry('赛车', 'Motorsport', 'モータースポーツ', '모터스포츠'),
  '網球': entry('网球', 'Tennis', 'テニス', '테니스'),
  '羽球': entry('羽毛球', 'Badminton', 'バドミントン', '배드민턴'),
  '桌球': entry('乒乓球', 'Table tennis', '卓球', '탁구'),
  '排球': entry('排球', 'Volleyball', 'バレーボール', '배구'),
  '高爾夫': entry('高尔夫', 'Golf', 'ゴルフ', '골프'),
  '格鬥': entry('格斗', 'Combat sports', '格闘技', '격투기'),
  'FIFA 世界盃': entry('FIFA 世界杯', 'FIFA World Cup', 'FIFAワールドカップ', 'FIFA 월드컵'),
  '英格蘭超級聯賽': entry('英格兰超级联赛', 'Premier League', 'プレミアリーグ', '프리미어리그'),
  '西班牙甲級聯賽': entry('西班牙甲级联赛', 'La Liga', 'ラ・リーガ', '라리가'),
  '德國甲級聯賽': entry('德国甲级联赛', 'Bundesliga', 'ブンデスリーガ', '분데스리가'),
  '義大利甲級聯賽': entry('意大利甲级联赛', 'Serie A', 'セリエA', '세리에 A'),
  '法國甲級聯賽': entry('法国甲级联赛', 'Ligue 1', 'リーグ・アン', '리그 1'),
  '歐洲冠軍聯賽': entry('欧洲冠军联赛', 'UEFA Champions League', 'UEFAチャンピオンズリーグ', 'UEFA 챔피언스리그'),
  'ATP 網球巡迴賽': entry('ATP 网球巡回赛', 'ATP Tour', 'ATPツアー', 'ATP 투어'),
  'WTA 網球巡迴賽': entry('WTA 网球巡回赛', 'WTA Tour', 'WTAツアー', 'WTA 투어'),
  '國際羽球賽事': entry('国际羽毛球赛事', 'International badminton', '国際バドミントン', '국제 배드민턴'),
  '國際桌球賽事': entry('国际乒乓球赛事', 'International table tennis', '国際卓球', '국제 탁구'),
  '國際排球賽事': entry('国际排球赛事', 'International volleyball', '国際バレーボール', '국제 배구'),
  'TheSportsDB 公開賽程': entry('TheSportsDB 公开赛程', 'TheSportsDB public schedule', 'TheSportsDB公開日程', 'TheSportsDB 공개 일정'),
  '英超': entry('英超', 'Premier League', 'プレミアリーグ', '프리미어리그'),
  '西甲': entry('西甲', 'La Liga', 'ラ・リーガ', '라리가'),
  '德甲': entry('德甲', 'Bundesliga', 'ブンデスリーガ', '분데스리가'),
  '義甲': entry('意甲', 'Serie A', 'セリエA', '세리에 A'),
  '法甲': entry('法甲', 'Ligue 1', 'リーグ・アン', '리그 1'),
  '歐冠': entry('欧冠', 'Champions League', 'チャンピオンズリーグ', '챔피언스리그')
};
