import type { Lang } from '../i18n/strings';

// Source-as-key i18n for the Fusion voice assistant. The Traditional-Chinese value in
// ASSISTANT_TEXT is the lookup key; ASSISTANT_TRANSLATIONS provides zh-CN / en / ja / ko.
// Strings that only appear in JSX can be written inline as t('…'); strings reused from the
// NLU / skill logic live in ASSISTANT_TEXT so the code and the dictionary never drift.

type Entry = Partial<Record<Exclude<Lang, 'zh-TW'>, string>>;

const entry = (zhCN: string, en: string, ja: string, ko: string): Entry => ({
  'zh-CN': zhCN,
  en,
  ja,
  ko
});

export const ASSISTANT_TEXT = {
  // ---- shell / panel ----
  category: '語音助理',
  title: 'Fusion 語音助理',
  tagline: '隨時待命的智慧助理',
  summon: '召喚語音助理',
  orbLabel: '呼叫 Fusion',
  close: '關閉助理',
  inputPlaceholder: '說點什麼，或輸入指令…',
  send: '傳送',
  micStart: '開始語音輸入',
  micStop: '停止聆聽',
  // ---- status ----
  statusIdle: '待命中',
  statusConnecting: '連線中…',
  statusRetrying: '重新連線中…',
  statusListening: '聆聽中…',
  statusThinking: '思考中…',
  statusSpeaking: '回應中…',
  statusModelLoading: 'Gemma 4 載入中…',
  // ---- hints ----
  hintText: '語音已待命；文字輸入可作為長問題或語音異常時的備用方式。',
  hintMicOff: '麥克風已停用，請至「隱私權與安全性」開啟後再使用語音。',
  hintMicError: 'Fusion OS 已允許麥克風，但 Windows 隱私權設定仍阻擋存取，請開啟桌面應用程式的麥克風權限。',
  hintVoiceError: '語音服務連線中斷，將自動重新連線；目前可先使用文字輸入。',
  hintNoStt: '此裝置不支援語音輸入，可改用文字輸入指令。',
  hintWake: '語音常駐待命中，可說「嗨 Fusion」、「Hey Fusion」或「OK Fusion」直接下指令。',
  hintNoServer: '本機語音服務正在背景啟動；首次使用會安裝語音元件，完成前仍可使用文字輸入。',
  voiceReady: '語音服務已連線',
  aiReady: 'Gemma 已就緒',
  // ---- greeting / help ----
  greeting: '你好，我是 Fusion 語音助理，有什麼可以為你服務的嗎？',
  greetingReply: '你好！需要我為你做什麼嗎？',
  thanksReply: '不客氣，隨時為你服務。',
  identityReply: '我是 Fusion OS 的內建語音助理，可以幫你開啟應用程式、查詢天氣與時間，或調整系統設定。',
  jokeReply: '為什麼程式設計師分不清萬聖節和聖誕節？因為 Oct 31 等於 Dec 25。',
  help: '我可以幫你：開啟應用程式（例如「打開系統設定」）、查詢天氣與時間、切換深色模式、調整亮度與音量、切換語言，或在網路上搜尋。直接說出來或輸入即可。',
  notUnderstood: '抱歉，我不太理解。你可以說「打開設定」、「今天天氣」或「現在幾點」。',
  // ---- quick suggestion chips ----
  chipTime: '現在幾點？',
  chipWeather: '今天天氣如何？',
  chipSettings: '打開系統設定',
  chipDark: '切換深色模式',
  chipApps: '開啟應用程式中心',
  chipHelp: '你會做什麼？',
  // ---- app launching ----
  openingApp: '正在開啟「{0}」。',
  appNotFound: '找不到名為「{0}」的應用程式，你可以說「開啟應用程式中心」查看全部。',
  // ---- time / date ----
  timeNow: '現在時間是 {0}。',
  dateToday: '今天是 {0}。',
  // ---- weather ----
  weatherLoading: '正在查詢{0}的天氣…',
  weatherResult: '{0}目前 {1}°，{2}，體感 {3}°，濕度 {4}%。',
  weatherError: '抱歉，目前無法取得天氣資訊，請稍後再試。',
  // ---- web search ----
  searching: '正在為你搜尋「{0}」。',
  openedWeb: '已為你開啟網頁區。',
  // ---- settings control ----
  setDark: '已切換到深色模式。',
  setLight: '已切換到淺色模式。',
  setNightOn: '已開啟夜間模式。',
  setNightOff: '已關閉夜間模式。',
  setBrighter: '已調亮畫面，目前亮度 {0}%。',
  setDimmer: '已調暗畫面，目前亮度 {0}%。',
  setVolume: '已將音量設為 {0}。',
  setMute: '已靜音。',
  setUnmute: '已取消靜音。',
  setTransparencyOn: '已開啟透明效果。',
  setTransparencyOff: '已關閉透明效果。',
  setAnimationsOn: '已開啟動畫效果。',
  setAnimationsOff: '已關閉動畫效果。',
  setContrastOn: '已開啟高對比。',
  setContrastOff: '已關閉高對比。',
  setWallpaper: '已為你更換桌布。',
  setLanguage: '已將顯示語言切換為{0}。',
  // ---- AI / Ollama ----
  aiFallback: 'Gemma 4 尚未就緒，這次已由 Fusion 內建理解接手。',
  aiThinking: 'AI 正在思考…',
  // ---- weather condition words (WMO codes) ----
  wClear: '晴朗',
  wMostlyClear: '大致晴朗',
  wPartly: '局部多雲',
  wOvercast: '陰天',
  wFog: '有霧',
  wDrizzle: '毛毛雨',
  wRain: '下雨',
  wHeavyRain: '大雨',
  wSnow: '下雪',
  wShowers: '陣雨',
  wThunder: '雷雨',
  // ---- settings section ----
  settingEnable: '啟用語音助理',
  settingEnableDesc: '在桌面顯示語音助理球，並可透過快捷鍵或語音喚醒。',
  settingVoice: '語音回覆',
  settingVoiceDesc: '以語音朗讀助理的回應（文字轉語音）。',
  settingWake: '語音喚醒',
  settingWakeDesc: '持續聆聽「嗨 Fusion／Hey Fusion／OK Fusion」，可在同一句話直接接續命令。',
  settingAi: '進階 AI 理解',
  settingAiDesc: '優先使用本機 Fusion 語音服務上的 Gemma 來理解更自然的對話；若未啟動則嘗試 Ollama，最後退回內建理解。',
  settingModel: 'Ollama 備援模型',
  settingModelHint: '改用 Ollama 時的模型名稱，例如 gemma3:12b（主要的 Gemma 透過語音服務執行）',
  settingServer: '語音服務位址',
  settingServerHint: 'Fusion OS 啟動時會自動開啟本機語音服務（Faster-Whisper + WebRTC VAD，Vosk 備援，Gemma 4）。',
  settingServerOn: '已偵測到語音服務',
  settingServerOff: '語音服務正在背景啟動',
  diagnosticsTitle: '麥克風即時診斷',
  diagnosticsDevice: '目前輸入裝置',
  diagnosticsInputLevel: '輸入音量',
  diagnosticsSignal: '訊號狀態',
  diagnosticsPackets: '音訊封包',
  diagnosticsSessions: '後端工作階段',
  diagnosticsLastText: '最後辨識',
  diagnosticsNoText: '尚無辨識結果',
  signalSilent: '未收到聲音',
  signalAudible: '已收到環境聲音',
  signalSpeech: '已偵測到人聲',
  hfAuthenticated: 'Hugging Face 已登入',
  hfNotAuthenticated: 'Hugging Face 尚未登入',
  hfPublicAccess: '公開模型，不需要 HF_TOKEN',
  settingHotkey: '快捷鍵',
  settingHotkeyDesc: '在桌面任意處按下即可呼叫語音助理。',
  settingOpenNow: '立即開啟語音助理'
} as const;

export const ASSISTANT_TRANSLATIONS: Record<string, Entry> = {
  [ASSISTANT_TEXT.category]: entry('语音助理', 'Voice Assistant', '音声アシスタント', '음성 비서'),
  [ASSISTANT_TEXT.title]: entry('Fusion 语音助理', 'Fusion Voice Assistant', 'Fusion 音声アシスタント', 'Fusion 음성 비서'),
  [ASSISTANT_TEXT.tagline]: entry('随时待命的智能助理', 'Your always-ready smart assistant', 'いつでも待機するスマートアシスタント', '언제나 대기하는 스마트 비서'),
  [ASSISTANT_TEXT.summon]: entry('召唤语音助理', 'Summon the voice assistant', '音声アシスタントを呼び出す', '음성 비서 호출'),
  [ASSISTANT_TEXT.orbLabel]: entry('呼叫 Fusion', 'Call Fusion', 'Fusion を呼ぶ', 'Fusion 호출'),
  [ASSISTANT_TEXT.close]: entry('关闭助理', 'Close assistant', 'アシスタントを閉じる', '비서 닫기'),
  [ASSISTANT_TEXT.inputPlaceholder]: entry('说点什么，或输入指令…', 'Say something, or type a command…', '話しかけるか、コマンドを入力…', '말을 걸거나 명령을 입력하세요…'),
  [ASSISTANT_TEXT.send]: entry('发送', 'Send', '送信', '보내기'),
  [ASSISTANT_TEXT.micStart]: entry('开始语音输入', 'Start voice input', '音声入力を開始', '음성 입력 시작'),
  [ASSISTANT_TEXT.micStop]: entry('停止聆听', 'Stop listening', '聞き取りを停止', '듣기 중지'),

  [ASSISTANT_TEXT.statusIdle]: entry('待命中', 'Standing by', '待機中', '대기 중'),
  [ASSISTANT_TEXT.statusConnecting]: entry('连接中…', 'Connecting…', '接続中…', '연결 중…'),
  [ASSISTANT_TEXT.statusRetrying]: entry('正在重新连接…', 'Reconnecting…', '再接続中…', '다시 연결 중…'),
  [ASSISTANT_TEXT.statusListening]: entry('聆听中…', 'Listening…', '聞いています…', '듣는 중…'),
  [ASSISTANT_TEXT.statusThinking]: entry('思考中…', 'Thinking…', '考えています…', '생각 중…'),
  [ASSISTANT_TEXT.statusSpeaking]: entry('回应中…', 'Responding…', '応答中…', '응답 중…'),
  [ASSISTANT_TEXT.statusModelLoading]: entry('Gemma 4 加载中…', 'Loading Gemma 4…', 'Gemma 4 を読み込み中…', 'Gemma 4 불러오는 중…'),

  [ASSISTANT_TEXT.hintText]: entry('语音已待命；文字输入可作为长问题或语音异常时的备用方式。', 'Voice is ready; text is available for long questions or as a fallback.', '音声は待機中です。長い質問や音声に問題がある場合は文字入力も使えます。', '음성이 대기 중입니다. 긴 질문이나 음성 문제 시 텍스트를 사용할 수 있습니다.'),
  [ASSISTANT_TEXT.hintMicOff]: entry('麦克风已停用，请至「隐私和安全性」开启后再使用语音。', 'The microphone is off. Enable it in Privacy & security to use voice.', 'マイクがオフです。音声を使うにはプライバシーとセキュリティで有効にしてください。', '마이크가 꺼져 있습니다. 음성을 사용하려면 개인정보 및 보안에서 켜세요.'),
  [ASSISTANT_TEXT.hintMicError]: entry('Fusion OS 已允许麦克风，但 Windows 隐私设置仍阻止访问，请开启桌面应用的麦克风权限。', 'Fusion OS allowed the microphone, but Windows privacy settings still block access. Enable microphone access for desktop apps.', 'Fusion OS ではマイクを許可済みですが、Windows のプライバシー設定でブロックされています。デスクトップ アプリのマイクを許可してください。', 'Fusion OS에서 마이크를 허용했지만 Windows 개인정보 설정이 차단하고 있습니다. 데스크톱 앱의 마이크 접근을 켜세요.'),
  [ASSISTANT_TEXT.hintVoiceError]: entry('语音服务连接中断，将自动重新连接；目前可先使用文字输入。', 'The voice service disconnected and will reconnect automatically. Text input remains available.', '音声サービスが切断されました。自動的に再接続します。現在は文字入力を利用できます。', '음성 서비스 연결이 끊어져 자동으로 다시 연결합니다. 지금은 텍스트 입력을 사용할 수 있습니다.'),
  [ASSISTANT_TEXT.hintNoStt]: entry('此设备不支持语音输入，可改用文字输入指令。', 'Voice input is not supported here; type your command instead.', 'この端末は音声入力に対応していません。テキストで入力してください。', '이 기기는 음성 입력을 지원하지 않습니다. 텍스트로 입력하세요.'),
  [ASSISTANT_TEXT.hintWake]: entry('语音常驻待命中，可说「嗨 Fusion」「Hey Fusion」或「OK Fusion」直接下指令。', 'Always listening for “Hey Fusion” or “OK Fusion”; continue with the command in the same sentence.', '「ねえ Fusion」「Hey Fusion」「OK Fusion」を常時待ち受け、同じ文で指示できます。', '“헤이 Fusion”, “Hey Fusion”, “OK Fusion”을 계속 듣고 같은 문장으로 명령할 수 있습니다.'),
  [ASSISTANT_TEXT.hintNoServer]: entry('本机语音服务正在后台启动；首次使用会安装语音组件，完成前仍可使用文字输入。', 'The local voice service is starting in the background. First use installs voice components; text remains available meanwhile.', 'ローカル音声サービスをバックグラウンドで起動中です。初回は音声部品を導入します。その間も文字入力を使えます。', '로컬 음성 서비스가 백그라운드에서 시작 중입니다. 첫 실행에는 음성 구성요소를 설치하며 그동안 텍스트를 사용할 수 있습니다.'),
  [ASSISTANT_TEXT.voiceReady]: entry('语音服务已连接', 'Voice service connected', '音声サービスに接続済み', '음성 서비스 연결됨'),
  [ASSISTANT_TEXT.aiReady]: entry('Gemma 已就绪', 'Gemma ready', 'Gemma 準備完了', 'Gemma 준비됨'),

  [ASSISTANT_TEXT.greeting]: entry('你好，我是 Fusion 语音助理，有什么可以为你服务的吗？', 'Hi, I’m the Fusion voice assistant. How can I help?', 'こんにちは、Fusion 音声アシスタントです。ご用件は？', '안녕하세요, Fusion 음성 비서입니다. 무엇을 도와드릴까요?'),
  [ASSISTANT_TEXT.greetingReply]: entry('你好！需要我为你做什么吗？', 'Hello! What can I do for you?', 'こんにちは！何をしましょうか？', '안녕하세요! 무엇을 도와드릴까요?'),
  [ASSISTANT_TEXT.thanksReply]: entry('不客气，随时为你服务。', 'You’re welcome — happy to help anytime.', 'どういたしまして。いつでもどうぞ。', '천만에요, 언제든 도와드릴게요.'),
  [ASSISTANT_TEXT.identityReply]: entry('我是 Fusion OS 的内置语音助理，可以帮你打开应用程序、查询天气与时间，或调整系统设置。', 'I’m the built-in Fusion OS voice assistant. I can open apps, check the weather and time, or adjust system settings.', '私は Fusion OS 内蔵の音声アシスタントです。アプリの起動、天気や時刻の確認、設定の変更ができます。', '저는 Fusion OS 내장 음성 비서입니다. 앱 열기, 날씨·시간 확인, 시스템 설정 변경을 도와드려요.'),
  [ASSISTANT_TEXT.jokeReply]: entry('为什么程序员分不清万圣节和圣诞节？因为 Oct 31 等于 Dec 25。', 'Why do programmers confuse Halloween and Christmas? Because Oct 31 equals Dec 25.', 'なぜプログラマーはハロウィンとクリスマスを混同する？ Oct 31 が Dec 25 と等しいから。', '프로그래머가 핼러윈과 크리스마스를 헷갈리는 이유? Oct 31이 Dec 25와 같아서요.'),
  [ASSISTANT_TEXT.help]: entry(
    '我可以帮你：打开应用程序（例如「打开系统设置」）、查询天气与时间、切换深色模式、调整亮度与音量、切换语言，或在网络上搜索。直接说出来或输入即可。',
    'I can: open apps (e.g. “open settings”), check weather and time, toggle dark mode, adjust brightness and volume, switch language, or search the web. Just say it or type it.',
    'できること：アプリ起動（例「設定を開いて」）、天気や時刻の確認、ダークモード切替、明るさ・音量調整、言語切替、ウェブ検索。話すか入力してください。',
    '제가 할 수 있는 것: 앱 열기(예: “설정 열어줘”), 날씨·시간 확인, 다크 모드 전환, 밝기·볼륨 조절, 언어 전환, 웹 검색. 말하거나 입력하세요.'
  ),
  [ASSISTANT_TEXT.notUnderstood]: entry('抱歉，我不太理解。你可以说「打开设置」「今天天气」或「现在几点」。', 'Sorry, I didn’t catch that. Try “open settings”, “today’s weather”, or “what time is it”.', 'すみません、よく分かりませんでした。「設定を開いて」「今日の天気」「今何時」などをお試しください。', '죄송해요, 이해하지 못했어요. “설정 열기”, “오늘 날씨”, “몇 시야”를 말해 보세요.'),

  [ASSISTANT_TEXT.chipTime]: entry('现在几点？', 'What time is it?', '今何時？', '몇 시야?'),
  [ASSISTANT_TEXT.chipWeather]: entry('今天天气如何？', 'How’s the weather?', '今日の天気は？', '오늘 날씨 어때?'),
  [ASSISTANT_TEXT.chipSettings]: entry('打开系统设置', 'Open settings', '設定を開く', '설정 열기'),
  [ASSISTANT_TEXT.chipDark]: entry('切换深色模式', 'Toggle dark mode', 'ダークモード切替', '다크 모드 전환'),
  [ASSISTANT_TEXT.chipApps]: entry('打开应用程序中心', 'Open App Center', 'アプリセンターを開く', '앱 센터 열기'),
  [ASSISTANT_TEXT.chipHelp]: entry('你会做什么？', 'What can you do?', '何ができる？', '무엇을 할 수 있어?'),

  [ASSISTANT_TEXT.openingApp]: entry('正在打开「{0}」。', 'Opening “{0}”.', '「{0}」を開いています。', '“{0}”을(를) 여는 중입니다.'),
  [ASSISTANT_TEXT.appNotFound]: entry('找不到名为「{0}」的应用程序，你可以说「打开应用程序中心」查看全部。', 'I couldn’t find an app called “{0}”. Say “open App Center” to see them all.', '「{0}」というアプリが見つかりません。「アプリセンターを開く」で一覧を確認できます。', '“{0}” 앱을 찾을 수 없습니다. “앱 센터 열기”로 전체를 확인하세요.'),

  [ASSISTANT_TEXT.timeNow]: entry('现在时间是 {0}。', 'It’s {0}.', '現在 {0} です。', '지금은 {0}입니다.'),
  [ASSISTANT_TEXT.dateToday]: entry('今天是 {0}。', 'Today is {0}.', '今日は {0} です。', '오늘은 {0}입니다.'),

  [ASSISTANT_TEXT.weatherLoading]: entry('正在查询{0}的天气…', 'Checking the weather in {0}…', '{0}の天気を確認しています…', '{0}의 날씨를 확인하는 중…'),
  [ASSISTANT_TEXT.weatherResult]: entry('{0}目前 {1}°，{2}，体感 {3}°，湿度 {4}%。', '{0}: {1}°, {2}, feels like {3}°, humidity {4}%.', '{0}は現在 {1}°、{2}、体感 {3}°、湿度 {4}%。', '{0}: 현재 {1}°, {2}, 체감 {3}°, 습도 {4}%.'),
  [ASSISTANT_TEXT.weatherError]: entry('抱歉，目前无法获取天气信息，请稍后再试。', 'Sorry, I couldn’t get the weather right now. Please try again later.', '申し訳ありません、天気情報を取得できませんでした。後でお試しください。', '죄송해요, 지금 날씨를 가져올 수 없습니다. 나중에 다시 시도하세요.'),

  [ASSISTANT_TEXT.searching]: entry('正在为你搜索「{0}」。', 'Searching for “{0}”.', '「{0}」を検索しています。', '“{0}”을(를) 검색합니다.'),
  [ASSISTANT_TEXT.openedWeb]: entry('已为你打开网页区。', 'I opened the Web Zone for you.', 'Web ゾーンを開きました。', '웹 구역을 열었습니다.'),

  [ASSISTANT_TEXT.setDark]: entry('已切换到深色模式。', 'Switched to dark mode.', 'ダークモードに切り替えました。', '다크 모드로 전환했습니다.'),
  [ASSISTANT_TEXT.setLight]: entry('已切换到浅色模式。', 'Switched to light mode.', 'ライトモードに切り替えました。', '라이트 모드로 전환했습니다.'),
  [ASSISTANT_TEXT.setNightOn]: entry('已开启夜间模式。', 'Night light is on.', 'ナイトモードをオンにしました。', '야간 모드를 켰습니다.'),
  [ASSISTANT_TEXT.setNightOff]: entry('已关闭夜间模式。', 'Night light is off.', 'ナイトモードをオフにしました。', '야간 모드를 껐습니다.'),
  [ASSISTANT_TEXT.setBrighter]: entry('已调亮画面，目前亮度 {0}%。', 'Brightness up — now {0}%.', '画面を明るくしました。現在 {0}%。', '밝기를 높였습니다 — 현재 {0}%.'),
  [ASSISTANT_TEXT.setDimmer]: entry('已调暗画面，目前亮度 {0}%。', 'Brightness down — now {0}%.', '画面を暗くしました。現在 {0}%。', '밝기를 낮췄습니다 — 현재 {0}%.'),
  [ASSISTANT_TEXT.setVolume]: entry('已将音量设为 {0}。', 'Volume set to {0}.', '音量を {0} にしました。', '볼륨을 {0}(으)로 설정했습니다.'),
  [ASSISTANT_TEXT.setMute]: entry('已静音。', 'Muted.', 'ミュートしました。', '음소거했습니다.'),
  [ASSISTANT_TEXT.setUnmute]: entry('已取消静音。', 'Unmuted.', 'ミュートを解除しました。', '음소거를 해제했습니다.'),
  [ASSISTANT_TEXT.setTransparencyOn]: entry('已开启透明效果。', 'Transparency on.', '透明効果をオンにしました。', '투명 효과를 켰습니다.'),
  [ASSISTANT_TEXT.setTransparencyOff]: entry('已关闭透明效果。', 'Transparency off.', '透明効果をオフにしました。', '투명 효과를 껐습니다.'),
  [ASSISTANT_TEXT.setAnimationsOn]: entry('已开启动画效果。', 'Animations on.', 'アニメーションをオンにしました。', '애니메이션을 켰습니다.'),
  [ASSISTANT_TEXT.setAnimationsOff]: entry('已关闭动画效果。', 'Animations off.', 'アニメーションをオフにしました。', '애니메이션을 껐습니다.'),
  [ASSISTANT_TEXT.setContrastOn]: entry('已开启高对比。', 'High contrast on.', 'ハイコントラストをオンにしました。', '고대비를 켰습니다.'),
  [ASSISTANT_TEXT.setContrastOff]: entry('已关闭高对比。', 'High contrast off.', 'ハイコントラストをオフにしました。', '고대비를 껐습니다.'),
  [ASSISTANT_TEXT.setWallpaper]: entry('已为你更换桌布。', 'Wallpaper changed.', '壁紙を変更しました。', '배경화면을 변경했습니다.'),
  [ASSISTANT_TEXT.setLanguage]: entry('已将显示语言切换为{0}。', 'Display language switched to {0}.', '表示言語を {0} に切り替えました。', '표시 언어를 {0}(으)로 전환했습니다.'),

  [ASSISTANT_TEXT.aiFallback]: entry('Gemma 4 尚未就绪，本次已由 Fusion 内置理解接管。', 'Gemma 4 is not ready yet; Fusion built-in understanding handled this request.', 'Gemma 4 はまだ準備中のため、今回は Fusion の内蔵理解が処理しました。', 'Gemma 4가 아직 준비되지 않아 이번 요청은 Fusion 내장 이해가 처리했습니다.'),
  [ASSISTANT_TEXT.aiThinking]: entry('AI 正在思考…', 'AI is thinking…', 'AI が考えています…', 'AI가 생각 중…'),

  [ASSISTANT_TEXT.wClear]: entry('晴朗', 'clear', '快晴', '맑음'),
  [ASSISTANT_TEXT.wMostlyClear]: entry('大致晴朗', 'mostly clear', 'おおむね晴れ', '대체로 맑음'),
  [ASSISTANT_TEXT.wPartly]: entry('局部多云', 'partly cloudy', '一部曇り', '부분적으로 흐림'),
  [ASSISTANT_TEXT.wOvercast]: entry('阴天', 'overcast', '曇り', '흐림'),
  [ASSISTANT_TEXT.wFog]: entry('有雾', 'foggy', '霧', '안개'),
  [ASSISTANT_TEXT.wDrizzle]: entry('毛毛雨', 'drizzle', '霧雨', '이슬비'),
  [ASSISTANT_TEXT.wRain]: entry('下雨', 'rain', '雨', '비'),
  [ASSISTANT_TEXT.wHeavyRain]: entry('大雨', 'heavy rain', '大雨', '폭우'),
  [ASSISTANT_TEXT.wSnow]: entry('下雪', 'snow', '雪', '눈'),
  [ASSISTANT_TEXT.wShowers]: entry('阵雨', 'showers', 'にわか雨', '소나기'),
  [ASSISTANT_TEXT.wThunder]: entry('雷雨', 'thunderstorm', '雷雨', '뇌우'),

  [ASSISTANT_TEXT.settingEnable]: entry('启用语音助理', 'Enable voice assistant', '音声アシスタントを有効化', '음성 비서 사용'),
  [ASSISTANT_TEXT.settingEnableDesc]: entry('在桌面显示语音助理球，并可通过快捷键或语音唤醒。', 'Show the assistant orb on the desktop and wake it by hotkey or voice.', 'デスクトップにアシスタントを表示し、ホットキーや音声で起動します。', '데스크톱에 비서 오브를 표시하고 단축키나 음성으로 깨웁니다.'),
  [ASSISTANT_TEXT.settingVoice]: entry('语音回复', 'Voice replies', '音声で返答', '음성 응답'),
  [ASSISTANT_TEXT.settingVoiceDesc]: entry('以语音朗读助理的回应（文字转语音）。', 'Read responses aloud (text to speech).', '応答を音声で読み上げます（テキスト読み上げ）。', '응답을 소리내어 읽습니다(TTS).'),
  [ASSISTANT_TEXT.settingWake]: entry('语音唤醒', 'Voice wake', '音声ウェイク', '음성 깨우기'),
  [ASSISTANT_TEXT.settingWakeDesc]: entry('持续聆听「嗨 Fusion／Hey Fusion／OK Fusion」，可在同一句话直接接续命令。', 'Listen continuously for “Hey Fusion / OK Fusion” and continue with the command in the same sentence.', '「ねえ Fusion／Hey Fusion／OK Fusion」を常時待ち受け、同じ文で指示できます。', '“헤이 Fusion / Hey Fusion / OK Fusion”을 계속 듣고 같은 문장으로 명령할 수 있습니다.'),
  [ASSISTANT_TEXT.settingAi]: entry('进阶 AI 理解', 'Advanced AI understanding', '高度な AI 理解', '고급 AI 이해'),
  [ASSISTANT_TEXT.settingAiDesc]: entry('优先使用本机 Fusion 语音服务上的 Gemma 来理解更自然的对话；若未启动则尝试 Ollama，最后退回内置理解。', 'Prefers the Gemma model running on your local Fusion Voice Server for natural dialogue; falls back to Ollama, then built-in understanding.', 'ローカルの Fusion 音声サービス上の Gemma を優先して自然な対話を理解します。未起動なら Ollama、最後は内蔵理解にフォールバック。', '로컬 Fusion 음성 서비스의 Gemma를 우선 사용해 자연스러운 대화를 이해하고, 없으면 Ollama, 마지막엔 내장 이해로 대체합니다.'),
  [ASSISTANT_TEXT.settingModel]: entry('Ollama 备援模型', 'Ollama fallback model', 'Ollama 予備モデル', 'Ollama 대체 모델'),
  [ASSISTANT_TEXT.settingModelHint]: entry('改用 Ollama 时的模型名称，例如 gemma3:12b（主要的 Gemma 通过语音服务运行）', 'Model name when falling back to Ollama, e.g. gemma3:12b (the main Gemma runs via the voice server)', 'Ollama にフォールバックする際のモデル名。例: gemma3:12b（メインの Gemma は音声サービスで実行）', 'Ollama로 대체할 때의 모델 이름, 예: gemma3:12b (주 Gemma는 음성 서비스에서 실행)'),
  [ASSISTANT_TEXT.settingServer]: entry('语音服务地址', 'Voice service URL', '音声サービスのアドレス', '음성 서비스 주소'),
  [ASSISTANT_TEXT.settingServerHint]: entry('Fusion OS 启动时会自动打开本机语音服务（Faster-Whisper + WebRTC VAD、Vosk 备用、Gemma 4）。', 'Fusion OS automatically starts the local voice service (Faster-Whisper + WebRTC VAD, Vosk fallback, Gemma 4).', 'Fusion OS の起動時にローカル音声サービス（Faster-Whisper + WebRTC VAD、Vosk 予備、Gemma 4）を自動起動します。', 'Fusion OS 시작 시 로컬 음성 서비스(Faster-Whisper + WebRTC VAD, Vosk 대체, Gemma 4)를 자동 실행합니다.'),
  [ASSISTANT_TEXT.settingServerOn]: entry('已检测到语音服务', 'Voice service detected', '音声サービスを検出', '음성 서비스 감지됨'),
  [ASSISTANT_TEXT.settingServerOff]: entry('语音服务正在后台启动', 'Voice service is starting in the background', '音声サービスをバックグラウンドで起動中', '음성 서비스가 백그라운드에서 시작 중'),
  [ASSISTANT_TEXT.diagnosticsTitle]: entry('麦克风实时诊断', 'Live microphone diagnostics', 'マイクのリアルタイム診断', '실시간 마이크 진단'),
  [ASSISTANT_TEXT.diagnosticsDevice]: entry('当前输入设备', 'Current input device', '現在の入力デバイス', '현재 입력 장치'),
  [ASSISTANT_TEXT.diagnosticsInputLevel]: entry('输入音量', 'Input level', '入力レベル', '입력 레벨'),
  [ASSISTANT_TEXT.diagnosticsSignal]: entry('信号状态', 'Signal status', '信号状態', '신호 상태'),
  [ASSISTANT_TEXT.diagnosticsPackets]: entry('音频数据包', 'Audio packets', '音声パケット', '오디오 패킷'),
  [ASSISTANT_TEXT.diagnosticsSessions]: entry('后端工作阶段', 'Backend sessions', 'バックエンド セッション', '백엔드 세션'),
  [ASSISTANT_TEXT.diagnosticsLastText]: entry('最后识别', 'Last transcription', '最後の認識結果', '마지막 인식'),
  [ASSISTANT_TEXT.diagnosticsNoText]: entry('尚无识别结果', 'No transcription yet', '認識結果はまだありません', '아직 인식 결과 없음'),
  [ASSISTANT_TEXT.signalSilent]: entry('未收到声音', 'No audio received', '音声を受信していません', '오디오 수신 없음'),
  [ASSISTANT_TEXT.signalAudible]: entry('已收到环境声音', 'Ambient audio received', '周囲の音を受信中', '주변 소리 수신됨'),
  [ASSISTANT_TEXT.signalSpeech]: entry('已检测到人声', 'Speech detected', '音声を検出', '음성 감지됨'),
  [ASSISTANT_TEXT.hfAuthenticated]: entry('Hugging Face 已登录', 'Hugging Face signed in', 'Hugging Face ログイン済み', 'Hugging Face 로그인됨'),
  [ASSISTANT_TEXT.hfNotAuthenticated]: entry('Hugging Face 尚未登录', 'Hugging Face not signed in', 'Hugging Face 未ログイン', 'Hugging Face 로그인 안 됨'),
  [ASSISTANT_TEXT.hfPublicAccess]: entry('公开模型，不需要 HF_TOKEN', 'Public model; HF_TOKEN is not required', '公開モデルのため HF_TOKEN は不要です', '공개 모델이며 HF_TOKEN이 필요하지 않습니다'),
  [ASSISTANT_TEXT.settingHotkey]: entry('快捷键', 'Hotkey', 'ホットキー', '단축키'),
  [ASSISTANT_TEXT.settingHotkeyDesc]: entry('在桌面任意处按下即可呼叫语音助理。', 'Press anywhere on the desktop to summon the assistant.', 'デスクトップのどこでも押すとアシスタントを呼び出せます。', '데스크톱 어디서나 눌러 비서를 호출합니다.'),
  [ASSISTANT_TEXT.settingOpenNow]: entry('立即打开语音助理', 'Open the assistant now', '今すぐアシスタントを開く', '지금 비서 열기')
};
